### model
model_name_or_path: /bjzhyai03/workhome/lvbohan/Meta-Llama-3-8B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
disable_shuffling: true

### dataset
dataset: math0
template: llama3
cutoff_len: 3860
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/math5
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.001
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 500